//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NodeJS.HttpParser {

public enum flags {
  F_CHUNKED = 1 << 0,
  F_CONNECTION_KEEP_ALIVE = 1 << 1,
  F_CONNECTION_CLOSE = 1 << 2,
  F_CONNECTION_UPGRADE = 1 << 3,
  F_TRAILING = 1 << 4,
  F_UPGRADE = 1 << 5,
  F_SKIPBODY = 1 << 6,
  F_CONTENTLENGTH = 1 << 7
}

}
