//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NodeJS.HttpParser {

public class HttpParser {
  public static void http_parser_type_set(SWIGTYPE_p_http_parser self, uint value) {
    HttpParserPINVOKE.http_parser_type_set(SWIGTYPE_p_http_parser.getCPtr(self), value);
  }

  public static uint http_parser_type_get(SWIGTYPE_p_http_parser self) {
    uint ret = HttpParserPINVOKE.http_parser_type_get(SWIGTYPE_p_http_parser.getCPtr(self));
    return ret;
  }

  public static void http_parser_flags_set(SWIGTYPE_p_http_parser self, uint value) {
    HttpParserPINVOKE.http_parser_flags_set(SWIGTYPE_p_http_parser.getCPtr(self), value);
  }

  public static uint http_parser_flags_get(SWIGTYPE_p_http_parser self) {
    uint ret = HttpParserPINVOKE.http_parser_flags_get(SWIGTYPE_p_http_parser.getCPtr(self));
    return ret;
  }

  public static void http_parser_state_set(SWIGTYPE_p_http_parser self, uint value) {
    HttpParserPINVOKE.http_parser_state_set(SWIGTYPE_p_http_parser.getCPtr(self), value);
  }

  public static uint http_parser_state_get(SWIGTYPE_p_http_parser self) {
    uint ret = HttpParserPINVOKE.http_parser_state_get(SWIGTYPE_p_http_parser.getCPtr(self));
    return ret;
  }

  public static void http_parser_header_state_set(SWIGTYPE_p_http_parser self, uint value) {
    HttpParserPINVOKE.http_parser_header_state_set(SWIGTYPE_p_http_parser.getCPtr(self), value);
  }

  public static uint http_parser_header_state_get(SWIGTYPE_p_http_parser self) {
    uint ret = HttpParserPINVOKE.http_parser_header_state_get(SWIGTYPE_p_http_parser.getCPtr(self));
    return ret;
  }

  public static void http_parser_index_set(SWIGTYPE_p_http_parser self, uint value) {
    HttpParserPINVOKE.http_parser_index_set(SWIGTYPE_p_http_parser.getCPtr(self), value);
  }

  public static uint http_parser_index_get(SWIGTYPE_p_http_parser self) {
    uint ret = HttpParserPINVOKE.http_parser_index_get(SWIGTYPE_p_http_parser.getCPtr(self));
    return ret;
  }

  public static void http_parser_lenient_http_headers_set(SWIGTYPE_p_http_parser self, uint value) {
    HttpParserPINVOKE.http_parser_lenient_http_headers_set(SWIGTYPE_p_http_parser.getCPtr(self), value);
  }

  public static uint http_parser_lenient_http_headers_get(SWIGTYPE_p_http_parser self) {
    uint ret = HttpParserPINVOKE.http_parser_lenient_http_headers_get(SWIGTYPE_p_http_parser.getCPtr(self));
    return ret;
  }

  public static void http_parser_nread_set(SWIGTYPE_p_http_parser self, SWIGTYPE_p_uint32_t value) {
    HttpParserPINVOKE.http_parser_nread_set(SWIGTYPE_p_http_parser.getCPtr(self), SWIGTYPE_p_uint32_t.getCPtr(value));
    if (HttpParserPINVOKE.SWIGPendingException.Pending) throw HttpParserPINVOKE.SWIGPendingException.Retrieve();
  }

  public static SWIGTYPE_p_uint32_t http_parser_nread_get(SWIGTYPE_p_http_parser self) {
    SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(HttpParserPINVOKE.http_parser_nread_get(SWIGTYPE_p_http_parser.getCPtr(self)), true);
    if (HttpParserPINVOKE.SWIGPendingException.Pending) throw HttpParserPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void http_parser_content_length_set(SWIGTYPE_p_http_parser self, SWIGTYPE_p_uint64_t value) {
    HttpParserPINVOKE.http_parser_content_length_set(SWIGTYPE_p_http_parser.getCPtr(self), SWIGTYPE_p_uint64_t.getCPtr(value));
    if (HttpParserPINVOKE.SWIGPendingException.Pending) throw HttpParserPINVOKE.SWIGPendingException.Retrieve();
  }

  public static SWIGTYPE_p_uint64_t http_parser_content_length_get(SWIGTYPE_p_http_parser self) {
    SWIGTYPE_p_uint64_t ret = new SWIGTYPE_p_uint64_t(HttpParserPINVOKE.http_parser_content_length_get(SWIGTYPE_p_http_parser.getCPtr(self)), true);
    if (HttpParserPINVOKE.SWIGPendingException.Pending) throw HttpParserPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void http_parser_http_major_set(SWIGTYPE_p_http_parser self, ushort value) {
    HttpParserPINVOKE.http_parser_http_major_set(SWIGTYPE_p_http_parser.getCPtr(self), value);
  }

  public static ushort http_parser_http_major_get(SWIGTYPE_p_http_parser self) {
    ushort ret = HttpParserPINVOKE.http_parser_http_major_get(SWIGTYPE_p_http_parser.getCPtr(self));
    return ret;
  }

  public static void http_parser_http_minor_set(SWIGTYPE_p_http_parser self, ushort value) {
    HttpParserPINVOKE.http_parser_http_minor_set(SWIGTYPE_p_http_parser.getCPtr(self), value);
  }

  public static ushort http_parser_http_minor_get(SWIGTYPE_p_http_parser self) {
    ushort ret = HttpParserPINVOKE.http_parser_http_minor_get(SWIGTYPE_p_http_parser.getCPtr(self));
    return ret;
  }

  public static void http_parser_status_code_set(SWIGTYPE_p_http_parser self, uint value) {
    HttpParserPINVOKE.http_parser_status_code_set(SWIGTYPE_p_http_parser.getCPtr(self), value);
  }

  public static uint http_parser_status_code_get(SWIGTYPE_p_http_parser self) {
    uint ret = HttpParserPINVOKE.http_parser_status_code_get(SWIGTYPE_p_http_parser.getCPtr(self));
    return ret;
  }

  public static void http_parser_method_set(SWIGTYPE_p_http_parser self, uint value) {
    HttpParserPINVOKE.http_parser_method_set(SWIGTYPE_p_http_parser.getCPtr(self), value);
  }

  public static uint http_parser_method_get(SWIGTYPE_p_http_parser self) {
    uint ret = HttpParserPINVOKE.http_parser_method_get(SWIGTYPE_p_http_parser.getCPtr(self));
    return ret;
  }

  public static void http_parser_http_errno_set(SWIGTYPE_p_http_parser self, uint value) {
    HttpParserPINVOKE.http_parser_http_errno_set(SWIGTYPE_p_http_parser.getCPtr(self), value);
  }

  public static uint http_parser_http_errno_get(SWIGTYPE_p_http_parser self) {
    uint ret = HttpParserPINVOKE.http_parser_http_errno_get(SWIGTYPE_p_http_parser.getCPtr(self));
    return ret;
  }

  public static void http_parser_upgrade_set(SWIGTYPE_p_http_parser self, uint value) {
    HttpParserPINVOKE.http_parser_upgrade_set(SWIGTYPE_p_http_parser.getCPtr(self), value);
  }

  public static uint http_parser_upgrade_get(SWIGTYPE_p_http_parser self) {
    uint ret = HttpParserPINVOKE.http_parser_upgrade_get(SWIGTYPE_p_http_parser.getCPtr(self));
    return ret;
  }

  public static void http_parser_data_set(SWIGTYPE_p_http_parser self, SWIGTYPE_p_void value) {
    HttpParserPINVOKE.http_parser_data_set(SWIGTYPE_p_http_parser.getCPtr(self), SWIGTYPE_p_void.getCPtr(value));
  }

  public static SWIGTYPE_p_void http_parser_data_get(SWIGTYPE_p_http_parser self) {
    global::System.IntPtr cPtr = HttpParserPINVOKE.http_parser_data_get(SWIGTYPE_p_http_parser.getCPtr(self));
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_http_parser new_http_parser() {
    global::System.IntPtr cPtr = HttpParserPINVOKE.new_http_parser();
    SWIGTYPE_p_http_parser ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_http_parser(cPtr, true);
    return ret;
  }

  public static void delete_http_parser(SWIGTYPE_p_http_parser self) {
    HttpParserPINVOKE.delete_http_parser(SWIGTYPE_p_http_parser.getCPtr(self));
  }

  public static void http_parser_settings_on_message_begin_set(SWIGTYPE_p_http_parser_settings self, SWIGTYPE_p_f_p_struct_http_parser__int value) {
    HttpParserPINVOKE.http_parser_settings_on_message_begin_set(SWIGTYPE_p_http_parser_settings.getCPtr(self), SWIGTYPE_p_f_p_struct_http_parser__int.getCPtr(value));
  }

  public static SWIGTYPE_p_f_p_struct_http_parser__int http_parser_settings_on_message_begin_get(SWIGTYPE_p_http_parser_settings self) {
    global::System.IntPtr cPtr = HttpParserPINVOKE.http_parser_settings_on_message_begin_get(SWIGTYPE_p_http_parser_settings.getCPtr(self));
    SWIGTYPE_p_f_p_struct_http_parser__int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_http_parser__int(cPtr, false);
    return ret;
  }

  public static void http_parser_settings_on_url_set(SWIGTYPE_p_http_parser_settings self, SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int value) {
    HttpParserPINVOKE.http_parser_settings_on_url_set(SWIGTYPE_p_http_parser_settings.getCPtr(self), SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int.getCPtr(value));
  }

  public static SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int http_parser_settings_on_url_get(SWIGTYPE_p_http_parser_settings self) {
    global::System.IntPtr cPtr = HttpParserPINVOKE.http_parser_settings_on_url_get(SWIGTYPE_p_http_parser_settings.getCPtr(self));
    SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int(cPtr, false);
    return ret;
  }

  public static void http_parser_settings_on_status_set(SWIGTYPE_p_http_parser_settings self, SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int value) {
    HttpParserPINVOKE.http_parser_settings_on_status_set(SWIGTYPE_p_http_parser_settings.getCPtr(self), SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int.getCPtr(value));
  }

  public static SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int http_parser_settings_on_status_get(SWIGTYPE_p_http_parser_settings self) {
    global::System.IntPtr cPtr = HttpParserPINVOKE.http_parser_settings_on_status_get(SWIGTYPE_p_http_parser_settings.getCPtr(self));
    SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int(cPtr, false);
    return ret;
  }

  public static void http_parser_settings_on_header_field_set(SWIGTYPE_p_http_parser_settings self, SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int value) {
    HttpParserPINVOKE.http_parser_settings_on_header_field_set(SWIGTYPE_p_http_parser_settings.getCPtr(self), SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int.getCPtr(value));
  }

  public static SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int http_parser_settings_on_header_field_get(SWIGTYPE_p_http_parser_settings self) {
    global::System.IntPtr cPtr = HttpParserPINVOKE.http_parser_settings_on_header_field_get(SWIGTYPE_p_http_parser_settings.getCPtr(self));
    SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int(cPtr, false);
    return ret;
  }

  public static void http_parser_settings_on_header_value_set(SWIGTYPE_p_http_parser_settings self, SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int value) {
    HttpParserPINVOKE.http_parser_settings_on_header_value_set(SWIGTYPE_p_http_parser_settings.getCPtr(self), SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int.getCPtr(value));
  }

  public static SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int http_parser_settings_on_header_value_get(SWIGTYPE_p_http_parser_settings self) {
    global::System.IntPtr cPtr = HttpParserPINVOKE.http_parser_settings_on_header_value_get(SWIGTYPE_p_http_parser_settings.getCPtr(self));
    SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int(cPtr, false);
    return ret;
  }

  public static void http_parser_settings_on_headers_complete_set(SWIGTYPE_p_http_parser_settings self, SWIGTYPE_p_f_p_struct_http_parser__int value) {
    HttpParserPINVOKE.http_parser_settings_on_headers_complete_set(SWIGTYPE_p_http_parser_settings.getCPtr(self), SWIGTYPE_p_f_p_struct_http_parser__int.getCPtr(value));
  }

  public static SWIGTYPE_p_f_p_struct_http_parser__int http_parser_settings_on_headers_complete_get(SWIGTYPE_p_http_parser_settings self) {
    global::System.IntPtr cPtr = HttpParserPINVOKE.http_parser_settings_on_headers_complete_get(SWIGTYPE_p_http_parser_settings.getCPtr(self));
    SWIGTYPE_p_f_p_struct_http_parser__int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_http_parser__int(cPtr, false);
    return ret;
  }

  public static void http_parser_settings_on_body_set(SWIGTYPE_p_http_parser_settings self, SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int value) {
    HttpParserPINVOKE.http_parser_settings_on_body_set(SWIGTYPE_p_http_parser_settings.getCPtr(self), SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int.getCPtr(value));
  }

  public static SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int http_parser_settings_on_body_get(SWIGTYPE_p_http_parser_settings self) {
    global::System.IntPtr cPtr = HttpParserPINVOKE.http_parser_settings_on_body_get(SWIGTYPE_p_http_parser_settings.getCPtr(self));
    SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_http_parser_p_q_const__char_size_t__int(cPtr, false);
    return ret;
  }

  public static void http_parser_settings_on_message_complete_set(SWIGTYPE_p_http_parser_settings self, SWIGTYPE_p_f_p_struct_http_parser__int value) {
    HttpParserPINVOKE.http_parser_settings_on_message_complete_set(SWIGTYPE_p_http_parser_settings.getCPtr(self), SWIGTYPE_p_f_p_struct_http_parser__int.getCPtr(value));
  }

  public static SWIGTYPE_p_f_p_struct_http_parser__int http_parser_settings_on_message_complete_get(SWIGTYPE_p_http_parser_settings self) {
    global::System.IntPtr cPtr = HttpParserPINVOKE.http_parser_settings_on_message_complete_get(SWIGTYPE_p_http_parser_settings.getCPtr(self));
    SWIGTYPE_p_f_p_struct_http_parser__int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_http_parser__int(cPtr, false);
    return ret;
  }

  public static void http_parser_settings_on_chunk_header_set(SWIGTYPE_p_http_parser_settings self, SWIGTYPE_p_f_p_struct_http_parser__int value) {
    HttpParserPINVOKE.http_parser_settings_on_chunk_header_set(SWIGTYPE_p_http_parser_settings.getCPtr(self), SWIGTYPE_p_f_p_struct_http_parser__int.getCPtr(value));
  }

  public static SWIGTYPE_p_f_p_struct_http_parser__int http_parser_settings_on_chunk_header_get(SWIGTYPE_p_http_parser_settings self) {
    global::System.IntPtr cPtr = HttpParserPINVOKE.http_parser_settings_on_chunk_header_get(SWIGTYPE_p_http_parser_settings.getCPtr(self));
    SWIGTYPE_p_f_p_struct_http_parser__int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_http_parser__int(cPtr, false);
    return ret;
  }

  public static void http_parser_settings_on_chunk_complete_set(SWIGTYPE_p_http_parser_settings self, SWIGTYPE_p_f_p_struct_http_parser__int value) {
    HttpParserPINVOKE.http_parser_settings_on_chunk_complete_set(SWIGTYPE_p_http_parser_settings.getCPtr(self), SWIGTYPE_p_f_p_struct_http_parser__int.getCPtr(value));
  }

  public static SWIGTYPE_p_f_p_struct_http_parser__int http_parser_settings_on_chunk_complete_get(SWIGTYPE_p_http_parser_settings self) {
    global::System.IntPtr cPtr = HttpParserPINVOKE.http_parser_settings_on_chunk_complete_get(SWIGTYPE_p_http_parser_settings.getCPtr(self));
    SWIGTYPE_p_f_p_struct_http_parser__int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_struct_http_parser__int(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_http_parser_settings new_http_parser_settings() {
    global::System.IntPtr cPtr = HttpParserPINVOKE.new_http_parser_settings();
    SWIGTYPE_p_http_parser_settings ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_http_parser_settings(cPtr, true);
    return ret;
  }

  public static void delete_http_parser_settings(SWIGTYPE_p_http_parser_settings self) {
    HttpParserPINVOKE.delete_http_parser_settings(SWIGTYPE_p_http_parser_settings.getCPtr(self));
  }

  public static void http_parser_url_field_set_set(SWIGTYPE_p_http_parser_url self, SWIGTYPE_p_uint16_t value) {
    HttpParserPINVOKE.http_parser_url_field_set_set(SWIGTYPE_p_http_parser_url.getCPtr(self), SWIGTYPE_p_uint16_t.getCPtr(value));
    if (HttpParserPINVOKE.SWIGPendingException.Pending) throw HttpParserPINVOKE.SWIGPendingException.Retrieve();
  }

  public static SWIGTYPE_p_uint16_t http_parser_url_field_set_get(SWIGTYPE_p_http_parser_url self) {
    SWIGTYPE_p_uint16_t ret = new SWIGTYPE_p_uint16_t(HttpParserPINVOKE.http_parser_url_field_set_get(SWIGTYPE_p_http_parser_url.getCPtr(self)), true);
    if (HttpParserPINVOKE.SWIGPendingException.Pending) throw HttpParserPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void http_parser_url_port_set(SWIGTYPE_p_http_parser_url self, SWIGTYPE_p_uint16_t value) {
    HttpParserPINVOKE.http_parser_url_port_set(SWIGTYPE_p_http_parser_url.getCPtr(self), SWIGTYPE_p_uint16_t.getCPtr(value));
    if (HttpParserPINVOKE.SWIGPendingException.Pending) throw HttpParserPINVOKE.SWIGPendingException.Retrieve();
  }

  public static SWIGTYPE_p_uint16_t http_parser_url_port_get(SWIGTYPE_p_http_parser_url self) {
    SWIGTYPE_p_uint16_t ret = new SWIGTYPE_p_uint16_t(HttpParserPINVOKE.http_parser_url_port_get(SWIGTYPE_p_http_parser_url.getCPtr(self)), true);
    if (HttpParserPINVOKE.SWIGPendingException.Pending) throw HttpParserPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_http_parser_url_field_data http_parser_url_field_data_get(SWIGTYPE_p_http_parser_url self) {
    global::System.IntPtr cPtr = HttpParserPINVOKE.http_parser_url_field_data_get(SWIGTYPE_p_http_parser_url.getCPtr(self));
    SWIGTYPE_p_http_parser_url_field_data ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_http_parser_url_field_data(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_http_parser_url new_http_parser_url() {
    global::System.IntPtr cPtr = HttpParserPINVOKE.new_http_parser_url();
    SWIGTYPE_p_http_parser_url ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_http_parser_url(cPtr, true);
    return ret;
  }

  public static void delete_http_parser_url(SWIGTYPE_p_http_parser_url self) {
    HttpParserPINVOKE.delete_http_parser_url(SWIGTYPE_p_http_parser_url.getCPtr(self));
  }

  public static void http_parser_url_field_data_off_set(SWIGTYPE_p_http_parser_url_field_data self, SWIGTYPE_p_uint16_t value) {
    HttpParserPINVOKE.http_parser_url_field_data_off_set(SWIGTYPE_p_http_parser_url_field_data.getCPtr(self), SWIGTYPE_p_uint16_t.getCPtr(value));
    if (HttpParserPINVOKE.SWIGPendingException.Pending) throw HttpParserPINVOKE.SWIGPendingException.Retrieve();
  }

  public static SWIGTYPE_p_uint16_t http_parser_url_field_data_off_get(SWIGTYPE_p_http_parser_url_field_data self) {
    SWIGTYPE_p_uint16_t ret = new SWIGTYPE_p_uint16_t(HttpParserPINVOKE.http_parser_url_field_data_off_get(SWIGTYPE_p_http_parser_url_field_data.getCPtr(self)), true);
    if (HttpParserPINVOKE.SWIGPendingException.Pending) throw HttpParserPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void http_parser_url_field_data_len_set(SWIGTYPE_p_http_parser_url_field_data self, SWIGTYPE_p_uint16_t value) {
    HttpParserPINVOKE.http_parser_url_field_data_len_set(SWIGTYPE_p_http_parser_url_field_data.getCPtr(self), SWIGTYPE_p_uint16_t.getCPtr(value));
    if (HttpParserPINVOKE.SWIGPendingException.Pending) throw HttpParserPINVOKE.SWIGPendingException.Retrieve();
  }

  public static SWIGTYPE_p_uint16_t http_parser_url_field_data_len_get(SWIGTYPE_p_http_parser_url_field_data self) {
    SWIGTYPE_p_uint16_t ret = new SWIGTYPE_p_uint16_t(HttpParserPINVOKE.http_parser_url_field_data_len_get(SWIGTYPE_p_http_parser_url_field_data.getCPtr(self)), true);
    if (HttpParserPINVOKE.SWIGPendingException.Pending) throw HttpParserPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_http_parser_url_field_data new_http_parser_url_field_data() {
    global::System.IntPtr cPtr = HttpParserPINVOKE.new_http_parser_url_field_data();
    SWIGTYPE_p_http_parser_url_field_data ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_http_parser_url_field_data(cPtr, true);
    return ret;
  }

  public static void delete_http_parser_url_field_data(SWIGTYPE_p_http_parser_url_field_data self) {
    HttpParserPINVOKE.delete_http_parser_url_field_data(SWIGTYPE_p_http_parser_url_field_data.getCPtr(self));
  }

  public static uint http_parser_version() {
    uint ret = HttpParserPINVOKE.http_parser_version();
    return ret;
  }

  public static void http_parser_init(SWIGTYPE_p_http_parser parser, http_parser_type type) {
    HttpParserPINVOKE.http_parser_init(SWIGTYPE_p_http_parser.getCPtr(parser), (int)type);
  }

  public static void http_parser_settings_init(SWIGTYPE_p_http_parser_settings settings) {
    HttpParserPINVOKE.http_parser_settings_init(SWIGTYPE_p_http_parser_settings.getCPtr(settings));
  }

  public static uint http_parser_execute(SWIGTYPE_p_http_parser parser, SWIGTYPE_p_http_parser_settings settings, string data, uint len) {
    uint ret = HttpParserPINVOKE.http_parser_execute(SWIGTYPE_p_http_parser.getCPtr(parser), SWIGTYPE_p_http_parser_settings.getCPtr(settings), data, len);
    return ret;
  }

  public static int http_should_keep_alive(SWIGTYPE_p_http_parser parser) {
    int ret = HttpParserPINVOKE.http_should_keep_alive(SWIGTYPE_p_http_parser.getCPtr(parser));
    return ret;
  }

  public static string http_method_str(http_method m) {
    string ret = HttpParserPINVOKE.http_method_str((int)m);
    return ret;
  }

  public static string http_status_str(http_status s) {
    string ret = HttpParserPINVOKE.http_status_str((int)s);
    return ret;
  }

  public static string http_errno_name(http_errno err) {
    string ret = HttpParserPINVOKE.http_errno_name((int)err);
    return ret;
  }

  public static string http_errno_description(http_errno err) {
    string ret = HttpParserPINVOKE.http_errno_description((int)err);
    return ret;
  }

  public static void http_parser_url_init(SWIGTYPE_p_http_parser_url u) {
    HttpParserPINVOKE.http_parser_url_init(SWIGTYPE_p_http_parser_url.getCPtr(u));
  }

  public static int http_parser_parse_url(string buf, uint buflen, int is_connect, SWIGTYPE_p_http_parser_url u) {
    int ret = HttpParserPINVOKE.http_parser_parse_url(buf, buflen, is_connect, SWIGTYPE_p_http_parser_url.getCPtr(u));
    return ret;
  }

  public static void http_parser_pause(SWIGTYPE_p_http_parser parser, int paused) {
    HttpParserPINVOKE.http_parser_pause(SWIGTYPE_p_http_parser.getCPtr(parser), paused);
  }

  public static int http_body_is_final(SWIGTYPE_p_http_parser parser) {
    int ret = HttpParserPINVOKE.http_body_is_final(SWIGTYPE_p_http_parser.getCPtr(parser));
    return ret;
  }

  public static void http_parser_set_max_header_size(SWIGTYPE_p_uint32_t size) {
    HttpParserPINVOKE.http_parser_set_max_header_size(SWIGTYPE_p_uint32_t.getCPtr(size));
    if (HttpParserPINVOKE.SWIGPendingException.Pending) throw HttpParserPINVOKE.SWIGPendingException.Retrieve();
  }

  public static readonly int HTTP_PARSER_VERSION_MAJOR = HttpParserPINVOKE.HTTP_PARSER_VERSION_MAJOR_get();
  public static readonly int HTTP_PARSER_VERSION_MINOR = HttpParserPINVOKE.HTTP_PARSER_VERSION_MINOR_get();
  public static readonly int HTTP_PARSER_VERSION_PATCH = HttpParserPINVOKE.HTTP_PARSER_VERSION_PATCH_get();
  public static readonly int HTTP_PARSER_STRICT = HttpParserPINVOKE.HTTP_PARSER_STRICT_get();
  public static readonly int HTTP_MAX_HEADER_SIZE = HttpParserPINVOKE.HTTP_MAX_HEADER_SIZE_get();
}

}
