//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NodeJS.HttpParser {

public enum http_parser_url_fields {
  UF_SCHEMA = 0,
  UF_HOST = 1,
  UF_PORT = 2,
  UF_PATH = 3,
  UF_QUERY = 4,
  UF_FRAGMENT = 5,
  UF_USERINFO = 6,
  UF_MAX = 7
}

}
