//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NodeJS.HttpParser {

class HttpParserPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="SWIGRegisterExceptionCallbacks_HttpParser")]
    public static extern void SWIGRegisterExceptionCallbacks_HttpParser(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_HttpParser")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_HttpParser(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_HttpParser(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_HttpParser(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(HttpParserPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(HttpParserPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="SWIGRegisterStringCallback_HttpParser")]
    public static extern void SWIGRegisterStringCallback_HttpParser(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_HttpParser(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static HttpParserPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_HTTP_PARSER_VERSION_MAJOR_get___")]
  public static extern int HTTP_PARSER_VERSION_MAJOR_get();

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_HTTP_PARSER_VERSION_MINOR_get___")]
  public static extern int HTTP_PARSER_VERSION_MINOR_get();

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_HTTP_PARSER_VERSION_PATCH_get___")]
  public static extern int HTTP_PARSER_VERSION_PATCH_get();

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_HTTP_PARSER_STRICT_get___")]
  public static extern int HTTP_PARSER_STRICT_get();

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_HTTP_MAX_HEADER_SIZE_get___")]
  public static extern int HTTP_MAX_HEADER_SIZE_get();

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_type_set___")]
  public static extern void http_parser_type_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_type_get___")]
  public static extern uint http_parser_type_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_flags_set___")]
  public static extern void http_parser_flags_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_flags_get___")]
  public static extern uint http_parser_flags_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_state_set___")]
  public static extern void http_parser_state_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_state_get___")]
  public static extern uint http_parser_state_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_header_state_set___")]
  public static extern void http_parser_header_state_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_header_state_get___")]
  public static extern uint http_parser_header_state_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_index_set___")]
  public static extern void http_parser_index_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_index_get___")]
  public static extern uint http_parser_index_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_lenient_http_headers_set___")]
  public static extern void http_parser_lenient_http_headers_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_lenient_http_headers_get___")]
  public static extern uint http_parser_lenient_http_headers_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_nread_set___")]
  public static extern void http_parser_nread_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_nread_get___")]
  public static extern global::System.IntPtr http_parser_nread_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_content_length_set___")]
  public static extern void http_parser_content_length_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_content_length_get___")]
  public static extern global::System.IntPtr http_parser_content_length_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_http_major_set___")]
  public static extern void http_parser_http_major_set(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_http_major_get___")]
  public static extern ushort http_parser_http_major_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_http_minor_set___")]
  public static extern void http_parser_http_minor_set(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_http_minor_get___")]
  public static extern ushort http_parser_http_minor_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_status_code_set___")]
  public static extern void http_parser_status_code_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_status_code_get___")]
  public static extern uint http_parser_status_code_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_method_set___")]
  public static extern void http_parser_method_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_method_get___")]
  public static extern uint http_parser_method_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_http_errno_set___")]
  public static extern void http_parser_http_errno_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_http_errno_get___")]
  public static extern uint http_parser_http_errno_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_upgrade_set___")]
  public static extern void http_parser_upgrade_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_upgrade_get___")]
  public static extern uint http_parser_upgrade_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_data_set___")]
  public static extern void http_parser_data_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_data_get___")]
  public static extern global::System.IntPtr http_parser_data_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_new_http_parser___")]
  public static extern global::System.IntPtr new_http_parser();

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_delete_http_parser___")]
  public static extern void delete_http_parser(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_message_begin_set___")]
  public static extern void http_parser_settings_on_message_begin_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_message_begin_get___")]
  public static extern global::System.IntPtr http_parser_settings_on_message_begin_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_url_set___")]
  public static extern void http_parser_settings_on_url_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_url_get___")]
  public static extern global::System.IntPtr http_parser_settings_on_url_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_status_set___")]
  public static extern void http_parser_settings_on_status_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_status_get___")]
  public static extern global::System.IntPtr http_parser_settings_on_status_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_header_field_set___")]
  public static extern void http_parser_settings_on_header_field_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_header_field_get___")]
  public static extern global::System.IntPtr http_parser_settings_on_header_field_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_header_value_set___")]
  public static extern void http_parser_settings_on_header_value_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_header_value_get___")]
  public static extern global::System.IntPtr http_parser_settings_on_header_value_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_headers_complete_set___")]
  public static extern void http_parser_settings_on_headers_complete_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_headers_complete_get___")]
  public static extern global::System.IntPtr http_parser_settings_on_headers_complete_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_body_set___")]
  public static extern void http_parser_settings_on_body_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_body_get___")]
  public static extern global::System.IntPtr http_parser_settings_on_body_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_message_complete_set___")]
  public static extern void http_parser_settings_on_message_complete_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_message_complete_get___")]
  public static extern global::System.IntPtr http_parser_settings_on_message_complete_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_chunk_header_set___")]
  public static extern void http_parser_settings_on_chunk_header_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_chunk_header_get___")]
  public static extern global::System.IntPtr http_parser_settings_on_chunk_header_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_chunk_complete_set___")]
  public static extern void http_parser_settings_on_chunk_complete_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_on_chunk_complete_get___")]
  public static extern global::System.IntPtr http_parser_settings_on_chunk_complete_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_new_http_parser_settings___")]
  public static extern global::System.IntPtr new_http_parser_settings();

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_delete_http_parser_settings___")]
  public static extern void delete_http_parser_settings(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_url_field_set_set___")]
  public static extern void http_parser_url_field_set_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_url_field_set_get___")]
  public static extern global::System.IntPtr http_parser_url_field_set_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_url_port_set___")]
  public static extern void http_parser_url_port_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_url_port_get___")]
  public static extern global::System.IntPtr http_parser_url_port_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_url_field_data_get___")]
  public static extern global::System.IntPtr http_parser_url_field_data_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_new_http_parser_url___")]
  public static extern global::System.IntPtr new_http_parser_url();

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_delete_http_parser_url___")]
  public static extern void delete_http_parser_url(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_url_field_data_off_set___")]
  public static extern void http_parser_url_field_data_off_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_url_field_data_off_get___")]
  public static extern global::System.IntPtr http_parser_url_field_data_off_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_url_field_data_len_set___")]
  public static extern void http_parser_url_field_data_len_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_url_field_data_len_get___")]
  public static extern global::System.IntPtr http_parser_url_field_data_len_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_new_http_parser_url_field_data___")]
  public static extern global::System.IntPtr new_http_parser_url_field_data();

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_delete_http_parser_url_field_data___")]
  public static extern void delete_http_parser_url_field_data(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_version___")]
  public static extern uint http_parser_version();

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_init___")]
  public static extern void http_parser_init(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_settings_init___")]
  public static extern void http_parser_settings_init(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_execute___")]
  public static extern uint http_parser_execute(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_should_keep_alive___")]
  public static extern int http_should_keep_alive(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_method_str___")]
  public static extern string http_method_str(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_status_str___")]
  public static extern string http_status_str(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_errno_name___")]
  public static extern string http_errno_name(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_errno_description___")]
  public static extern string http_errno_description(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_url_init___")]
  public static extern void http_parser_url_init(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_parse_url___")]
  public static extern int http_parser_parse_url(string jarg1, uint jarg2, int jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_pause___")]
  public static extern void http_parser_pause(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_body_is_final___")]
  public static extern int http_body_is_final(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("HttpParser", EntryPoint="CSharp_NodeJSfHttpParser_http_parser_set_max_header_size___")]
  public static extern void http_parser_set_max_header_size(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
